Repository tensorflow/minigo, pull requests merged in 2018-09, with the labels that each got.

#411 add missing build dep
  cc/BUILD
Labels: size/XS

#413 Remove petname dependency.
  requirements.txt
  shipname.py
Labels: size/XS

#404 Better sampling
  example_buffer.py
  local_rl_loop.py
Labels: size/M

#418 Make use_random_rotation (for inference) a flag
  dual_net.py
Labels: size/S

#424 fix includes
  cc/main.cc
Labels: size/XS

#429 Add top-level comment in SGFs containing models used
  cc/main.cc
  cc/mcts_player.h
  cc/sgf.cc
  cc/sgf.h
Labels: size/M

#430 Print to dbg to avoid gtp errors
  strategies.py
Labels: size/XS

#439 Add missing include
  cc/file/utils_shared.cc
Labels: size/XS

#442 Add performance logging to inference server
  cc/main.cc
  inference_worker.py
Labels: size/M

#447 Replace argh library with fire library.
  cluster/evaluator/launch_eval.py
  dual_net.py
  example_buffer.py
  main.py
  oneoffs/resign_analysis.py
  requirements.txt
  rl_loop.py
  rl_runner.py
Labels: size/M

#449 Add fire to requirements.txt
  requirements.txt
Labels: size/XS

#448 Tie break most visited path with action score
  mcts.py
Labels: size/XS

#453 Minor cleanup of markdown in README.md
  README.md
Labels: size/M

#451 Moving .bazelrc according to best practices.
  .gitignore
  tools/bazel.rc
Labels: size/XS

#445 Correctly return gtp error for illegal play_move
  strategies.py
Labels: size/XS

#458 Add a oneoff script to generate positions embeddings from the bottom of the shared trunk
  oneoffs/embeddings.py
Labels: size/L

#467 V12 changes
  cc/main.cc
  cluster/cluster-up-tpu.sh
  cluster/selfplay/tpu-player-deployment.yaml
  cluster/selfplay/tpu_wrapper.sh
Labels: size/S

#462 Fix indexing error in oneoffs/embeddings.py
  oneoffs/embeddings.py
Labels: size/S

#464 Add tiebreak to pick_move
  mcts.py
  oneoffs/position_pv.py
  strategies.py
Labels: size/S

#463 Turn embeddings into t-SNE coordinates for graphing
  oneoffs/embeddings.py
  oneoffs/embeddings_graphs.py
Labels: size/L
