Repository tensorflow/minigo, pull requests merged in 2018-10, with the labels that each got.

#470 Add license header
  cc/dual_net/factory.cc
  cc/dual_net/factory.h
  example_buffer.py
  minigui/serve.py
  oneoffs/compare_examples.py
  oneoffs/heatmap.py
  oneoffs/l2_cost_by_var.py
  oneoffs/oneoff_utils.py
  oneoffs/position_pv.py
  oneoffs/prepare_bigquery.py
  oneoffs/training_curve.py
  tests/run_tests.py
Labels: size/L

#477 Update ABSL to latest version
  WORKSPACE
Labels: size/S

#479 replace python with python3 for unit tests
  mask_flags.py
  rl_loop/local_integration_test.py
  rl_loop/train_and_validate.py
Labels: size/S

#481 break pb export out of dual_net export
  dual_net.py
  ratings/ratings.py
Labels: size/XS

#480 Replace iomanip with absl formatting functions
  cc/BUILD
  cc/gtp_player.cc
  cc/mcts_node.cc
  cc/mcts_player.cc
  cc/position.cc
  cc/sgf.cc
Labels: size/M

#465 Move batching out of inference server
  cc/dual_net/BUILD
  cc/dual_net/batching_dual_net.cc
  cc/dual_net/batching_dual_net.h
  cc/dual_net/dual_net.cc
  cc/dual_net/dual_net.h
  cc/dual_net/factory.cc
  cc/dual_net/factory.h
  cc/dual_net/fake_net.cc
  cc/dual_net/fake_net.h
  cc/dual_net/inference_server.cc
  cc/dual_net/inference_server.h
  cc/dual_net/inference_server_test.cc
  cc/dual_net/lite_dual_net.cc
  cc/dual_net/lite_dual_net.h
  cc/dual_net/tf_dual_net.cc
  cc/dual_net/tf_dual_net.h
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/main.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
Labels: size/XL

#482 Make DualNet implementations private
  cc/dual_net/BUILD
  cc/dual_net/lite_dual_net.cc
  cc/dual_net/lite_dual_net.h
  cc/dual_net/tf_dual_net.cc
  cc/dual_net/tf_dual_net.h
Labels: size/M

#486 Summary step fix
  dual_net.py
Labels: size/S

#485 TfDualNet Multi-GPU
  cc/dual_net/BUILD
  cc/dual_net/tf_dual_net.cc
Labels: size/L

#484 V13 image builds
  cluster/selfplay/Dockerfile.tpu
  cluster/selfplay/Makefile
  cluster/selfplay/launch-tpu-deployment.sh
  cluster/selfplay/tpu-player-deployment.yaml
  cluster/selfplay/tpu-player.yaml
  inference_worker.py
  mask_flags.py
  rl_loop/distributed_flags
  rl_loop/selfplay.py
  tests/test_mask_flags.py
Labels: size/L

#491 Correctly format C++ files touched by Bigtable
  cc/main.cc
  cc/tf_bt_utils.cc
  cc/tf_bt_utils_dummy.cc
  cc/tf_utils.cc
  cc/tf_utils.h
Labels: size/M

#493 Use GPUs (in TfDualNet) only when --define=gpu=1 is set.
  cc/config/BUILD
  cc/dual_net/BUILD
  cc/dual_net/tf_dual_net.cc
Labels: size/S

#494 Fix incorrect bigtable check.
  cc/main.cc
Labels: size/XS

#495 Upgrade cc/configure_tensorflow.sh
  cc/configure_tensorflow.sh
  requirements.txt
Labels: size/M

#503 Allow MG_CHECK, MG_FATAL in any namespace
  cc/check.h
Labels: size/S

#502 Set frugal garbage collection policy on Bigtable
  cluster/utils.sh
Labels: size/XS

#505 BigtableClient requires TF 1.11+
  README.md
Labels: size/XS

#504 Create C++ tool for converting ZLIB TFRecord files to Bigtable rows
  cc/BUILD
  cc/tf_bt_utils.cc
  cc/tf_bt_utils_dummy.cc
  cc/tf_utils.h
  cc/tfrzz_to_cbt.cc
Labels: size/L

#507 Change run_tests.py to allow testing individual modules
  README.md
  tests/run_tests.py
  tests/test_strategies.py
Labels: size/S

#514 Add compiled Minigui frontend JavaScript
  .gitignore
  cc/dual_net/lite_dual_net.cc
  minigui/static/app.js
  minigui/static/base.js
  minigui/static/board.js
  minigui/static/demo_app.js
  minigui/static/gtp_socket.js
  minigui/static/heat_map.js
  minigui/static/kiosk.js
  minigui/static/layer.js
  minigui/static/log.js
  minigui/static/util.js
  minigui/static/view.js
  minigui/static/winrate_graph.js
Labels: size/XXL

#516 Explain some magic in freeze_graph_tpu
  dual_net.py
Labels: size/XS

#518 Fix unused tf.asserts
  symmetries.py
Labels: size/S

#524 add missing build dep
  cc/dual_net/BUILD
Labels: size/XS

#525 BUILD file cleanup
  cc/BUILD
Labels: size/XS

#498 Eval: parallel games and even mode.
  cc/main.cc
Labels: size/L

#515 Bigtable input available for training
  .pylintrc
  bigtable_input.py
  cc/tf_bt_utils.cc
  preprocessing.py
  requirements.txt
  train.py
Labels: size/L

#527 rename FakeNet -> FakeDualNet and make available as an inference engine
  cc/BUILD
  cc/dual_net/BUILD
  cc/dual_net/factory.cc
  cc/dual_net/fake_dual_net.cc
  cc/dual_net/fake_dual_net.h
  cc/mcts_player_test.cc
Labels: size/M

#528 Run pylint3 even if venv is not activated
  test.sh
Labels: size/XS

#533 Cleaning up dependencies from #523.
  cc/BUILD
  cc/dual_net/BUILD
  cc/dual_net/batching_dual_net.cc
  cc/dual_net/batching_dual_net.h
  cc/dual_net/factory.cc
Labels: size/S

#511 Update RESULTS.md for v12
  RESULTS.md
Labels: size/L

#521 Allow editing of FLAGS before passing to model_fn
  dual_net.py
  oneoffs/swa.py
Labels: size/M

#536 Better handle multiple golden chunks in TPU train
  preprocessing.py
  tests/test_preprocessing.py
  validate.py
Labels: size/M

#537 Add interleave argument documentation
  preprocessing.py
Labels: size/XS

#519 Remove obsolete dependencies
  requirements.txt
Labels: size/XS

#539 Allow export without bootstrap
  bootstrap.py
  dual_net.py
Labels: size/S
