Repository tensorflow/minigo, pull requests merged in 2018-06, with the labels that each got.

#254 update readme to remove `generation-num` arg to `train-dir`
  README.md
Labels: size/XS

#253 clean up some dead code
  notes.txt
  sgf_wrapper.py
  strategies.py
Labels: size/S

#255 Fix flaky position_test
  cc/position_test.cc
Labels: size/XS

#251 Docker images for CGOS
  .gitignore
  cc/gtp_player.cc
  cc/gtp_player.h
  cluster/base/Makefile
  cluster/cgos/Dockerfile
  cluster/cgos/Makefile
  cluster/cgos/cgos-player.yaml
  cluster/selfplay/Dockerfile-cc
  cluster/selfplay/Makefile
Labels: size/M

#258 Tpu experiments
  dual_net.py
  main.py
  preprocessing.py
  test.sh
  testing/Dockerfile.v2
  testing/version-v2.json
Labels: size/L

#263 Quality of Life improvements to GTP engines
  cc/gtp_player.cc
  cc/gtp_player.h
  gtp_cmd_handlers.py
  gtp_wrapper.py
Labels: size/S

#262 Set gpu_options.allow_growth = true for c++ engine
  cc/dual_net/tf_dual_net.cc
Labels: size/XS

#268 minor cleanup of Dataset.repeat()
  preprocessing.py
Labels: size/S

#270 Fix eval dates
  cluster/evaluator/evaluator_cc_wrapper.sh
  cluster/evaluator/evaluator_wrapper.sh
  cluster/evaluator/gpu-evaluator.yaml
  notes.txt
Labels: size/S

#266 Move symmetry handling code up into the MctsPlayer code
  cc/BUILD
  cc/dual_net/BUILD
  cc/dual_net/dual_net.cc
  cc/dual_net/dual_net.h
  cc/dual_net/dual_net_test.cc
  cc/dual_net/fake_net.cc
  cc/dual_net/fake_net.h
  cc/dual_net/inference_server.cc
  cc/dual_net/inference_server_test.cc
  cc/dual_net/tf_dual_net.cc
  cc/dual_net/tf_dual_net.h
  cc/main.cc
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/position.h
Labels: size/XL

#272 add a "cross-eval" command to launch_eval, making it easier to launch…
  cluster/evaluator/cc-evaluator.yaml
  cluster/evaluator/launch_eval.py
Labels: size/M

#274 Clean up C++ code
  cc/BUILD
  cc/README.md
  cc/config/BUILD
  cc/config/minigo.bzl
  cc/coord.cc
  cc/dual_net/BUILD
  cc/dual_net/inference_server.cc
  cc/dual_net/tf_dual_net.cc
  cc/file/BUILD
  cc/main.cc
  requirements.txt
Labels: size/L

#273 ensure tf_records is cast to a list if shuffle_records is false
  preprocessing.py
Labels: size/XS

#269 update dual_net for use with tpus
  dual_net.py
  local_rl_loop.py
  main.py
  preprocessing.py
  tests/test_dual_net.py
Labels: size/M

#279 generate non-zero values in test_preprocessing.py
  tests/test_preprocessing.py
Labels: size/XS

#284 Bootstrap function fix
  dual_net.py
Labels: size/XS

#283 Oneoff SWA script
  oneoffs/swa.py
Labels: size/L

#289 Clean up eval-launcher scripts
  cluster/evaluator/cc-evaluator.yaml
  cluster/evaluator/launch_eval.py
  fsdb.py
  notes.txt
Labels: size/L

#267 Speedup random.shuffle by converting deque to list
  example_buffer.py
Labels: size/M

#285 Adjust c_puct to 0.96
  cc/constants.h
  mcts.py
Labels: size/XS

#290 Convert training_curve to absl.flags
  oneoffs/heatmap.py
  oneoffs/position_pv.py
  oneoffs/training_curve.py
Labels: size/M

#291 Make dual_net.py model setup more verbose
  dual_net.py
Labels: size/M

#294 l2_cost oneoff script
  oneoffs/l2_cost_by_var.py
Labels: size/L
