Repository tensorflow/minigo, pull requests merged in 2018-08, with the labels that each got.

#354 Slow window
  example_buffer.py
Labels: size/XS

#360 Update constants
  cc/constants.h
  cc/main.cc
  cluster/evaluator/evaluator_cc_wrapper.sh
  cluster/selfplay/cc_wrapper.sh
  cluster/selfplay/player_wrapper.sh
  cluster/selfplay/tpu_wrapper.sh
  mcts.py
Labels: size/M

#361 Don't divide steps by NUM_TPUS if passed from command line
  dual_net.py
Labels: size/XS

#320 Flake8 fixes
  dual_net.py
  example_buffer.py
  fsdb.py
  go.py
  gtp.py
  gtp_cmd_handlers.py
  inference_worker.py
  local_rl_loop.py
  main.py
  mcts.py
  minigui/serve.py
  oneoffs/compare_examples.py
  oneoffs/heatmap.py
  oneoffs/l2_cost_by_var.py
  oneoffs/oneoff_utils.py
  oneoffs/position_pv.py
  oneoffs/prepare_bigquery.py
  oneoffs/rotate_examples.py
  oneoffs/symmetry_analysis.py
  preprocessing.py
  rl_loop.py
  selfplay.py
  sgf_wrapper.py
  strategies.py
  symmetries.py
  tests/test_coords.py
  tests/test_dual_net.py
  tests/test_features.py
  tests/test_go.py
  tests/test_mcts.py
  tests/test_preprocessing.py
  tests/test_strategies.py
  tests/test_utils.py
Labels: size/L

#364 Unify soft_pick temperature cutoff code
  cc/mcts_player.cc
  strategies.py
Labels: size/S

#328 Add tie breaker to fix num_readouts=1
  cc/mcts_player.cc
  strategies.py
Labels: size/S

#366 Improvements to several debug print statements
  dual_net.py
  example_buffer.py
  fsdb.py
  gtp.py
  gtp_cmd_handlers.py
  gtp_engine.py
  inference_worker.py
  local_rl_loop.py
  main.py
  rl_runner.py
  selfplay.py
  strategies.py
  utils.py
Labels: size/L

#376 Only load minigui cmd handle in minigui mode
  gtp.py
  gtp_cmd_handlers.py
  minigui/serve.py
Labels: size/S

#377 Upgrade dbg print wrapper
  utils.py
Labels: size/XS

#378 Remove final 'rm -rf' from configure_tensorflow.sh
  cc/configure_tensorflow.sh
Labels: size/XS

#365 Simplify most visited path code
  cc/mcts_node.cc
  mcts.py
Labels: size/M

#380 pylint over test files
  test.sh
  tests/test_dual_net.py
  tests/test_go.py
  tests/test_preprocessing.py
  tests/test_sgf_wrapper.py
  tests/test_strategies.py
  tests/test_utils.py
  utils.py
Labels: size/M

#383 fix typo in test
  cc/mcts_node_test.cc
Labels: size/XS

#385 Change all unittest.assert() to be assert(expected, actual)
  tests/test_coords.py
  tests/test_features.py
  tests/test_mcts.py
  tests/test_preprocessing.py
  tests/test_sgf_wrapper.py
  tests/test_shipname.py
  tests/test_strategies.py
  tests/test_utils.py
Labels: size/L

#388 Quality of Life improvements for tests
  mcts.py
  test.sh
Labels: size/M

#390 Undefined name: import unittest in test_sgf_wrapper.py
  tests/test_sgf_wrapper.py
Labels: size/XS

#398 Fix calls to utils.dbg
  gtp_cmd_handlers.py
  minigui/serve.py
Labels: size/S

#399 Tag inference engine build targets as manual
  cc/dual_net/BUILD
Labels: size/XS

#400 Add fc_width flag for remote inference
  cc/dual_net/factory.cc
Labels: size/XS
