Repository tensorflow/minigo, pull requests merged in 2018-03, with the labels that each got.

#118 Initial commit of C++ port.
  .gitignore
  WORKSPACE
  cc/BUILD
  cc/README.md
  cc/benchmark.BUILD
  cc/color.cc
  cc/color.h
  cc/configure_tensorflow.sh
  cc/constants.h
  cc/coord.cc
  cc/coord.h
  cc/coord_test.cc
  cc/dual_net.cc
  cc/dual_net.h
  cc/group.cc
  cc/group.h
  cc/inline_vector.h
  cc/play_game.cc
  cc/position.cc
  cc/position.h
  cc/position_benchmark.cc
  cc/position_test.cc
  cc/stone.h
  cc/tf_test.cc
  cc/tiny_set.h
Labels: size/XXL

#127 Add a little echo command
  rl_loop.py
Labels: lgtm, size/XS

#130 GTP engine enhancements for minigui
  go.py
  strategies.py
Labels: size/M

#131 Fixed parameter in training_curve.py
  oneoffs/training_curve.py
Labels: size/S

#132 Better TQDM in training_curve
  oneoffs/training_curve.py
Labels: needs-ok-to-test, size/S

#133 Start work on the evaluation server.
  README.md
  cluster/common.sh
  cluster/var-status.sh
  main.py
  requirements.txt
  yomi/README.md
  yomi/simple_eval.py
Labels: size/L

#99 update RESULTS.md with links to our 9x9 files
  RESULTS.md
Labels: size/M

#135 Miscellaneous improvements as I'm going through the codebase
  README.md
  go.py
  main.py
  strategies.py
Labels: size/M

#134 Choose two players to play a match
  cluster/init-credentials.sh
  cluster/unset-common.sh
  cluster/utils.sh
  dual_net.py
  requirements.txt
  yomi/README.md
  yomi/simple_eval.py
Labels: size/L

#138 Refactor utility methods out of oneoff/training_curve
  oneoffs/oneoff_utils.py
  oneoffs/training_curve.py
Labels: size/L

#128 Adds C++ MctsPlayer
  WORKSPACE
  cc/BUILD
  cc/algorithm.h
  cc/color.cc
  cc/color.h
  cc/constants.h
  cc/coord.cc
  cc/coord.h
  cc/dual_net.cc
  cc/dual_net.h
  cc/dual_net_test.cc
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/play_game.cc
  cc/position.cc
  cc/position.h
  cc/position_benchmark.cc
  cc/position_test.cc
  cc/random.cc
  cc/random.h
  cc/random_test.cc
  cc/symmetries.h
  cc/symmetries_test.cc
  cc/test_utils.cc
  cc/test_utils.h
  cc/tf_test.cc
Labels: size/XXL
