Repository tensorflow/minigo, pull requests merged in 2018-02, with the labels that each got.

#81 Improve coords.py
  .gitignore
  README.md
  coords.py
  go.py
  gtp_extensions.py
  gtp_wrapper.py
  mcts.py
  oneoffs/training_curve.py
  preprocessing.py
  selfplay_mcts.py
  sgf_wrapper.py
  strategies.py
  tests/test_coords.py
  tests/test_go.py
  tests/test_mcts.py
  tests/test_preprocessing.py
  tests/test_sgf_wrapper.py
  tests/test_strategies.py
  tests/test_symmetries.py
Labels: lgtm, size/XL

#82 Fix some lint errors.
  evaluation.py
  local_rl_loop.py
  rl_runner.py
Labels: size/XS

#85 Fix shbang
  test.sh
Labels: size/XS

#79 Add a V2 prow-bootstrap.py harness config.
  README.md
  test.sh
  testing/Dockerfile.v2
  testing/Makefile
  testing/README.md
  testing/bootstrap.sh
  testing/bootstrap_v2.sh
  testing/version-v2.json
  testing/version.json
Labels: lgtm, size/L

#86 Re-add Set gpu_options.allow_growth = True
  dual_net.py
Labels: size/XS

#80 Add `validate` to DualNetworkTrainer. Add command to main.py
  dual_net.py
  local_rl_loop.py
  main.py
  preprocessing.py
  rl_loop.py
Labels: size/L

#92 Adds validate call to rl_runner. Fixes #43
  dual_net.py
  main.py
  rl_loop.py
  rl_runner.py
Labels: lgtm, size/S

#101 Add param to strategies.MCTSPlayer.to_sgf to optionally include comments in sgf output
  main.py
  strategies.py
Labels: size/S

#107 Fix utils sh
  cluster/Makefile
  cluster/cluster-up-gpu-large
  cluster/common.sh
  cluster/utils.sh
Labels: lgtm, size/S

#108 resign threshold param not making it through rl_loop.py => main.py
  rl_loop.py
Labels: lgtm, size/XS

#109 Remove anti-affinity constraint for scheduling gpu-player
  cluster/gpu-player.yaml
Labels: size/S

#110 Log policy entropy
  dual_net.py
Labels: lgtm, size/XS

#111 Fix evaluate
  .pylintrc
  evaluation.py
  local_rl_loop.py
  main.py
  strategies.py
Labels: lgtm, size/L

#115 simplify code in evaluate a bit further
  evaluation.py
  local_rl_loop.py
Labels: size/S

#112 Refactor cluster directory.
  .gitignore
  cluster/README.md
  cluster/bootstrap-model.sh
  cluster/cluster-down
  cluster/cluster-down.sh
  cluster/cluster-up-cpu.sh
  cluster/cluster-up-gpu-large.sh
  cluster/cluster-up-gpu.sh
  cluster/common.sh
  cluster/destroy
  cluster/destroy.sh
  cluster/selfplay/Dockerfile
  cluster/selfplay/Dockerfile.gpu
  cluster/selfplay/Makefile
  cluster/selfplay/README.md
  cluster/selfplay/cpu-player.yaml
  cluster/selfplay/deploy-cpu-player.sh
  cluster/selfplay/deploy-gpu-player.sh
  cluster/selfplay/gpu-player.yaml
  cluster/selfplay/gpu-provision-daemonset.yaml
  cluster/selfplay/player_wrapper.sh
  cluster/unset_common.sh
  cluster/utils.sh
Labels: size/XL

#113 Estimator rewrite
  dual_net.py
  local_rl_loop.py
  main.py
  preprocessing.py
  rl_loop.py
  rl_runner.py
  tests/test_dual_net.py
  tests/test_preprocessing.py
Labels: size/XL
