Repository tensorflow/minigo, pull requests merged in 2018-12, with the labels that each got.

#590 Add bigtable eval tags
  cc/main.cc
  cc/tf_bt_utils.cc
  cc/tf_bt_utils_dummy.cc
  cc/tf_utils.h
Labels: size/S

#594 make gRPC use proto v3.6.0 instead of v3.5.0
  WORKSPACE
Labels: size/XS

#588 Allow [tt] for pass
  cc/coord.cc
Labels: size/XS

#600 Add GameQueue.create()
  bigtable_input.py
Labels: size/S

#606 Use simple, effective Dataset.shuffle
  bigtable_input.py
Labels: size/S

#602 V14 more fixes
  bigtable_input.py
  cluster/cluster-up-tpu.sh
  cluster/selfplay/tpu-player-deployment-nr.yaml
  cluster/selfplay/tpu-player-deployment.yaml
  dual_net.py
  rl_loop/distributed_flags
  rl_loop/distributed_flags_nr
  rl_loop/train_and_validate.py
  rl_loop/update_resign_threshold.py
  validate.py
Labels: size/M

#611 DualNet cleanup
  cc/dual_net/dual_net_test.cc
  cc/dual_net/lite_dual_net.cc
  cc/dual_net/tf_dual_net.cc
  cc/dual_net/tpu_dual_net.cc
  cc/dual_net/trt_dual_net.cc
  cc/logging.cc
Labels: size/M

#604 s/EVAL_VERSION_TAG/VERSION_TAG
  cluster/common.sh
  cluster/unset-common.sh
Labels: size/XS

#618 call NewGame from GtpPlayer construction to fully initialize everything
  cc/gtp_player.cc
Labels: size/XS

#619 Add average depth, max depth, and num leaf nodes.
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_player.cc
Labels: size/M

#609 Change the 'wait for games' to trigger at end of training.
  bigtable_input.py
  preprocessing.py
  rl_loop/distributed_flags
  train.py
Labels: size/L

#615 Add methods to help trim and repair GameQueues
  bigtable_input.py
Labels: size/L

#623 Create BT input datasets within input_fn
  train.py
Labels: size/S

#624 Turn rl_loop train & validate into a k8s deployment
  bigtable_input.py
  cluster/trainer/Dockerfile
  cluster/trainer/Makefile
  cluster/trainer/deploy-trainer.sh
  cluster/trainer/tpu-trainer-deployment.yaml
  mask_flags.py
  rl_loop/distributed_flags
  rl_loop/train_and_validate.py
  train.py
Labels: size/L

#621 Use `multiprocessing.Pool` to speed up game trim
  .pylintrc
  bigtable_input.py
Labels: size/L

#627 Trainer job fixes
  bigtable_input.py
  cluster/trainer/Dockerfile
  cluster/trainer/tpu-trainer-deployment.yaml
  rl_loop/distributed_flags
  rl_loop/train_and_validate.py
  train.py
Labels: size/M

#625 Calibrator k8s job
  bigtable_input.py
  cluster/calibrator/Dockerfile
  cluster/calibrator/Makefile
  cluster/calibrator/calibrator-deployment.yaml
  mask_flags.py
  rl_loop/fsdb.py
  rl_loop/update_resign_threshold.py
  tests/test_flags
Labels: size/L

#595 Sharp positions oneoff
  oneoffs/oneoff_utils.py
  oneoffs/sharp_positions.py
Labels: size/L

#601 Initial work on eval-server
  cluster/eval_server/README.md
  cluster/eval_server/launch_eval.py
  cluster/evaluator/launch_eval.py
Labels: size/L
