Repository tensorflow/minigo, pull requests merged in 2018-11, with the labels that each got.

#542 Fix tensor name mismatch between dual_net.py and tpu_dual_net.cc
  cc/dual_net/tpu_dual_net.cc
Labels: size/XS

#546 Small python changes.
  rl_loop/example_buffer.py
  strategies.py
Labels: size/XS

#535 Store move count per game, use shuffle buffer
  bigtable_input.py
  cc/tf_bt_utils.cc
Labels: size/L

#551 Fixing pull-tf-minigo-cc presubmit test.
  cc/BUILD
  cc/test.sh
Labels: size/S

#552 During self-play, write bleakest move to Bigtable
  cc/main.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/tf_bt_utils.cc
Labels: size/L

#534 Optionally depend on TensorFlow through bazel.
  .bazelrc
  .gitignore
  BUILD
  WORKSPACE
  cc/BUILD
  cc/README.md
  cc/config/BUILD
  cc/configure_tensorflow.sh
  cc/cuda_configure.bzl
  cc/dual_net/BUILD
  cc/dual_net/tf_dual_net.cc
  cc/file/BUILD
  cc/json.BUILD
  cc/tensorflow/BUILD
  cc/tensorflow/build.sh
  cc/tensorflow/tensorflow.patch
  cc/tensorflow_configure.bzl
  cc/tensorrt_parsers_configure.bzl
  tensorflow.bazelrc
  testing/Dockerfile.v2
  testing/Makefile
  testing/bootstrap_v2.sh
  testing/setup.sh
  tf_configure.bazelrc
  tools/bazel.rc
  user.bazelrc
  workspace.bzl
Labels: size/XL

#557 Bigtable input can now wait for fresh games
  bigtable_input.py
  preprocessing.py
Labels: size/M

#556 flake8 + autopep8
  bootstrap.py
  dual_net.py
  evaluate.py
  go.py
  mask_flags.py
  mcts.py
  minigui/serve.py
  ratings/ratings.py
  rl_loop/bootstrap.py
  strategies.py
  tests/test_mask_flags.py
  train.py
  utils.py
  validate.py
Labels: size/M

#555 Script to create distillation training data
  oneoffs/distillation.py
Labels: size/L

#561 Fetch and sort bleakest moves from game range
  bigtable_input.py
Labels: size/S

#562 Link against libm. Required after PR #534
  cc/BUILD
Labels: size/XS

#563 Clean up SGF parsing & handle escaped sequences
  cc/BUILD
  cc/gtp_player.cc
  cc/main.cc
  cc/sgf.cc
  cc/sgf.h
  cc/sgf_test.cc
Labels: size/L

#564 Batch the inferences made when loading an SGF.
  cc/BUILD
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/test_utils.cc
  minigui/position.ts
  minigui/static/position.js
  minigui/static/study.js
  minigui/study.ts
Labels: size/L

#565 Forgot to force cell value to integer
  bigtable_input.py
Labels: size/XS

#567 update cluster readme, selfplay makefile and docker image
  cluster/README.md
  cluster/selfplay/Makefile
  cluster/selfplay/README.md
Labels: size/M

#566 Create CBT instance only if needed
  cluster/create_table.sh
  cluster/utils.sh
Labels: size/M

#574 move source tree out of base image
  cluster/base/Dockerfile
  cluster/base/Makefile
  cluster/selfplay/Dockerfile-cc
  cluster/selfplay/Dockerfile-tpu
  testing/Dockerfile.v2
  testing/Makefile
Labels: size/M

#573 Refactor of some bigtable code
  cc/tf_bt_utils.cc
  cc/tf_utils.h
  cluster/utils.sh
Labels: size/M

#575 Evaluate win rate for loaded SGFs in the background
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  minigui/demo.ts
  minigui/kiosk.ts
  minigui/layer.ts
  minigui/position.ts
  minigui/static/demo.js
  minigui/static/kiosk.js
  minigui/static/layer.js
  minigui/static/position.js
  minigui/static/study.js
  minigui/static/winrate_graph.js
  minigui/study.ts
  minigui/winrate_graph.ts
Labels: size/XL

#577 fix build warnings when using c++11
  cc/dual_net/dual_net_test.cc
  cc/dual_net/tf_dual_net.cc
  cc/position_test.cc
  cc/random_test.cc
  cc/symmetries_test.cc
  cc/thread_safe_queue_test.cc
Labels: size/L

#578 Read games from two CBT tables
  bigtable_input.py
Labels: size/M

#581 Update README.md
  README.md
Labels: size/XS

#582 Updated using google::cloud::bigtable in tf_bt_utils
  cc/tf_bt_utils.cc
  cc/tf_utils.h
Labels: size/M

#571 Write eval results to bigtable for CC Eval games.
  cc/README.md
  cc/main.cc
  cc/tf_bt_utils.cc
  cc/tf_bt_utils_dummy.cc
  cc/tf_utils.h
  cc/tfrzz_to_cbt.cc
Labels: size/L

#584 Add validate_misc.py script
  oneoffs/validate_misc.py
Labels: size/M
