Repository tensorflow/minigo, pull requests merged in 2018-04, with the labels that each got.

#141 Add separate configs for building C++ minigo for 9x9 and 19x19 boards.
  .bazelrc
  cc/BUILD
  cc/README.md
  cc/config/BUILD
  cc/config/bazelrc
  cc/config/minigo_test.bzl
  cc/dual_net_test.cc
  cc/position.h
  cc/random.cc
Labels: size/L

#144 Add oneoff/heatmap.py and add to oneoff_utils
  oneoffs/heatmap.py
  oneoffs/oneoff_utils.py
  oneoffs/training_curve.py
  sgf_wrapper.py
Labels: size/L

#148 Minigui
  .gitignore
  gtp_extensions.py
  gtp_wrapper.py
  mcts.py
  minigui/README.md
  minigui/board.ts
  minigui/graph.ts
  minigui/gtp_socket.ts
  minigui/log.ts
  minigui/minigui.ts
  minigui/serve.py
  minigui/static/index.html
  minigui/static/require/LICENSE
  minigui/static/require/require.js
  minigui/static/socketio/LICENSE
  minigui/static/socketio/socket.io.min.js
  minigui/static/style.css
  minigui/util.ts
  strategies.py
  tsconfig.json
Labels: size/XXL

#150 deduplicated sgf_parsing code in oneoff_utils
  oneoffs/heatmap.py
  oneoffs/oneoff_utils.py
  oneoffs/training_curve.py
  sgf_wrapper.py
Labels: size/M

#152 Fixes required to get C++ code compiling on VMs
  cc/BUILD
  cc/configure_tensorflow.sh
  cc/mcts_node.cc
  cc/position.cc
  cc/position.h
Labels: size/M

#155 Adds basic C++ SGF parsing and generation.
  cc/BUILD
  cc/config/minigo_test.bzl
  cc/coord.cc
  cc/coord.h
  cc/coord_test.cc
  cc/move.cc
  cc/move.h
  cc/sgf.cc
  cc/sgf.h
  cc/sgf_test.cc
Labels: size/XL

#153 add a hook for echoing training performance to stdout
  dual_net.py
Labels: lgtm, size/S

#158 Add a __init__.py in tests/ so I can run the tests locally.
  tests/__init__.py
Labels: size/XS

#159 Update minigui README / docs
  minigui/README.md
  minigui/requirements.txt
  minigui/serve.py
Labels: size/S

#151 Backfill global step
  main.py
  rl_loop.py
Labels: size/M

#165 Adds GTP & Minigui support to C++ code
  cc/BUILD
  cc/constants.h
  cc/coord.cc
  cc/coord.h
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/main.cc
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/sgf.cc
  gtp_extensions.py
  minigui/graph.ts
  minigui/gtp_socket.ts
  minigui/minigui.ts
  minigui/serve.py
Labels: size/XXL

#167 Add flags infrastructure to main.py
  main.py
  requirements.txt
Labels: size/XS

#166 Rotate dataset with py_func
  preprocessing.py
  tests/test_preprocessing.py
Labels: needs-ok-to-test, size/L

#169 Swap out hyperparams in strategies, mcts and set up unit test flag co…
  go.py
  local_rl_loop.py
  main.py
  mcts.py
  rl_loop.py
  strategies.py
  test.sh
  tests/run_tests.py
  tests/test_flags
  tests/test_mcts.py
  tests/test_strategies.py
Labels: size/L

#168 Improve C++ build configs.
  .bazelrc
  cc/BUILD
  cc/README.md
  cc/config/BUILD
  cc/config/bazelrc
  cc/config/minigo.bzl
  cc/config/minigo_test.bzl
  cc/init.cc
Labels: size/L

#176 Set default minigui backend to the python impl (avoids blaze build dep)
  minigui/README.md
  minigui/serve.py
Labels: size/M

#173 Add base_dir flag to prepare_bigquery
  oneoffs/prepare_bigquery.py
Labels: size/M

#161 "Freeze" graph for inference after training, bootstrap
  main.py
Labels: size/S

#149 Update tf.nn.softmax_cross_entropy_with_logits to v2
  dual_net.py
Labels: size/XS

#178 Dockerize our cc-selfplay binary
  cc/configure_tensorflow.sh
  cluster/selfplay/Makefile
  cluster/selfplay/cc-Dockerfile
  cluster/selfplay/cc_wrapper.sh
Labels: size/L

#139 Symmetry analysis
  README.md
  dual_net.py
  oneoffs/inspect_game.py
  oneoffs/symmetry_analysis.py
  preprocessing.py
Labels: size/L

#172 Replace num_readouts and resign_threshold with flag versions
  README.md
  cluster/selfplay/player_wrapper.sh
  evaluation.py
  gtp_extensions.py
  gtp_wrapper.py
  local_rl_loop.py
  main.py
  mcts.py
  minigui/serve.py
  oneoffs/position_pv.py
  rl_loop.py
  selfplay_mcts.py
  strategies.py
Labels: size/L

#174 update docs for estimator and new tests
  README.md
  main.py
  testing/Dockerfile
  testing/Dockerfile.v2
  testing/Makefile
  testing/version.json
Labels: size/L

#180 change back to cross_entropy_v2
  dual_net.py
Labels: size/XS

#160 Merge v5 changes back into master
  cluster/cluster-up-gpu-large.sh
  cluster/selfplay/gpu-player.yaml
  cluster/selfplay/player_wrapper.sh
  dual_net.py
  evaluation.py
  example_buffer.py
  gtp_wrapper.py
  local_rl_loop.py
  main.py
  mcts.py
  notes.txt
  oneoffs/resign_analysis.py
  rl_loop.py
  rl_runner.py
  strategies.py
  utils.py
Labels: size/L

#185 Lint
  .pylintrc
  dual_net.py
  features.py
  main.py
  rl_runner.py
  shipname.py
  tests/test_utils.py
  utils.py
Labels: size/L

#186 remove dead gather code
  evaluation.py
  main.py
  preprocessing.py
  rl_loop.py
  tests/test_preprocessing.py
  utils.py
Labels: size/L

#183 Add more details about the testing process.
  testing/README.md
  testing/bootstrap.sh
  testing/version-v2.json
Labels: size/M

#187 fix local_rl_loop.py to use temp directory
  example_buffer.py
  local_rl_loop.py
Labels: size/S

#184 Replace num_parallel with flag
  evaluation.py
  selfplay_mcts.py
  strategies.py
  tests/test_strategies.py
Labels: size/M

#190 train with an incremental number of steps instead of max_steps
  dual_net.py
  main.py
  preprocessing.py
Labels: size/S
