Repository tensorflow/minigo, pull requests merged in 2018-07, with the labels that each got.

#302 clear board before loadsgf
  cc/gtp_player.cc
  gtp_cmd_handlers.py
Labels: size/XS

#303 Update cluster Makefiles
  cluster/README.md
  cluster/base/Makefile
  cluster/cgos/Dockerfile
  cluster/cgos/Makefile
  cluster/evaluator/Dockerfile-cc
  cluster/evaluator/Makefile
  cluster/evaluator/launch_eval.py
  cluster/selfplay/Dockerfile-cc
  cluster/selfplay/Makefile
Labels: size/M

#304 Update cc-base default tag
  cluster/cgos/Dockerfile
  cluster/evaluator/Dockerfile-cc
  cluster/selfplay/Dockerfile-cc
Labels: size/XS

#292 Small model tweaks
  dual_net.py
Labels: size/XS

#278 Rotate in chunker
  oneoffs/rotate_examples.py
  preprocessing.py
Labels: size/L

#308 Cleanups
  dual_net.py
  features.py
  go.py
  local_rl_loop.py
  main.py
Labels: size/S

#261 change -march=ivybridge to native
  cc/configure_tensorflow.sh
  cluster/base/Dockerfile
  cluster/base/Makefile
Labels: size/S

#299 Zero out illegal moves
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player_test.cc
  cc/position.cc
  cc/position.h
  mcts.py
  tests/test_mcts.py
Labels: size/L

#311 Always use tf.contrib.summary
  dual_net.py
Labels: size/M

#312 Refactor get_estimator() to gracefully handle TPU
  dual_net.py
Labels: size/M

#295 Only add D-noise to legal moves
  cc/mcts_node.cc
  cc/mcts_node_test.cc
  mcts.py
  tests/test_mcts.py
Labels: size/M

#310 Create dockerfiles and deployments for tpu selfplay
  cc/dual_net/inference_server.cc
  cc/main.cc
  cluster/base/Makefile
  cluster/cluster-up-tpu.sh
  cluster/selfplay/Dockerfile.tpu
  cluster/selfplay/Makefile
  cluster/selfplay/launch-tpu-deployment.sh
  cluster/selfplay/tpu-player-deployment.yaml
  cluster/selfplay/tpu-player.yaml
  cluster/selfplay/tpu_wrapper.sh
  dual_net.py
  inference_worker.py
  notes.txt
Labels: size/L

#318 Typo in Variable name: pi1 --> pi
  tests/test_preprocessing.py
Labels: size/XS

#321 Refactor preprocessing in preparation for TPU rotation
  preprocessing.py
  tests/test_preprocessing.py
Labels: size/L

#322 TPU random_rotation
  preprocessing.py
  symmetries.py
  test.sh
  tests/test_preprocessing.py
Labels: size/M

#324 Always print the top 15 possible moves
  cc/main.cc
  cc/mcts_node.cc
Labels: size/XS

#325 update minigui fetch-and-run
  minigui/fetch-and-run.sh
  minigui/minigui-common.sh
  minigui/serve.py
Labels: size/S

#327 Move test dashboard link in README
  README.md
Labels: size/XS

#326 Add value_head_weight for supervised training
  dual_net.py
Labels: size/S

#330 Trainer changes
  dual_net.py
  rl_loop.py
  rl_runner.py
Labels: size/S

#332 Fix configure_tensorflow
  cc/configure_tensorflow.sh
Labels: size/S

#334 Remove stray character
  cc/configure_tensorflow.sh
Labels: size/XS

#337 fix lints
  rl_runner.py
Labels: size/XS

#342 Enable random rotation for both GPU and TPU train()
  dual_net.py
Labels: size/S

#344 changes from live gatherer box
  example_buffer.py
Labels: size/S

#345 Clean up automatic steps calculation
  dual_net.py
Labels: size/XS

#343 Trainer changes
  dual_net.py
  preprocessing.py
Labels: size/XS

#341 Refactor selfplay, gtp
  .pylintrc
  README.md
  evaluation.py
  gtp.py
  gtp_wrapper.py
  local_rl_loop.py
  main.py
  minigui/serve.py
  oneoffs/oneoff_utils.py
  oneoffs/training_curve.py
  rl_loop.py
  selfplay.py
  selfplay_mcts.py
Labels: size/XL

#346 Reset tf.metrics after summary logs
  dual_net.py
Labels: size/M
