Repository tensorflow/minigo, pull requests merged in 2018-05, with the labels that each got.

#194 Guess the model path rather than making the user suffer
  cluster/minigui/run-local.sh
  minigui/README.md
Labels: size/S

#195 If sourcing defaults in bash commands, run in a subshell.
  cluster/bootstrap-model.sh
  cluster/cluster-down.sh
  cluster/cluster-up-cpu.sh
  cluster/cluster-up-gpu-large.sh
  cluster/cluster-up-gpu.sh
  cluster/cluster-up-simple.sh
  cluster/init-credentials.sh
  cluster/minigui/run-local.sh
  minigui/fetch-and-run.sh
Labels: size/XL

#196 Remove {} nonsense
  cluster/bootstrap-model.sh
  cluster/cluster-down.sh
  cluster/cluster-up-cpu.sh
  cluster/cluster-up-gpu-large.sh
  cluster/cluster-up-gpu.sh
  cluster/cluster-up-simple.sh
  cluster/init-credentials.sh
  cluster/minigui/run-local.sh
  cluster/var-status.sh
Labels: size/L

#197 Update Minigui to use Python-slim
  cluster/common.sh
  cluster/minigui/Dockerfile
Labels: size/XS

#201 Introduce fsdb.py
  .pylintrc
  cluster/selfplay/player_wrapper.sh
  example_buffer.py
  fsdb.py
  local_rl_loop.py
  rl_loop.py
  rl_runner.py
Labels: size/L

#208 Change C++ to handle virtual losses the same way as the Python code
  cc/BUILD
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player_test.cc
Labels: size/L

#198 Cc selfplay docker
  cc/configure_tensorflow.sh
  cluster/common.sh
  cluster/selfplay/Makefile
  cluster/selfplay/cc-Dockerfile
  cluster/selfplay/cc-player.yaml
  cluster/selfplay/cc_wrapper.sh
  cluster/selfplay/deploy-cc-player.sh
  main.py
Labels: size/L

#177 New flag for prepare_bigquery to only include top move
  oneoffs/prepare_bigquery.py
Labels: size/M

#209 fix wrapper script to correctly count games. Fix output of duration …
  cc/mcts_player.cc
  cluster/selfplay/cc_wrapper.sh
Labels: size/S

#211 update hparams
  dual_net.py
Labels: size/S

#212 Misc fixes from trainer box
  dual_net.py
  main.py
  rl_loop.py
  rl_runner.py
Labels: size/M

#213 Update mcts_player.cc
  cc/mcts_player.cc
Labels: size/XS

#216 Fix gke gpu scheduling
  cluster/selfplay/cc-player.yaml
  cluster/selfplay/cc_wrapper.sh
  cluster/selfplay/gpu-player.yaml
Labels: size/S

#214 Replaces pygtp with our own simple GTP engine.
  .pylintrc
  cc/gtp_player.cc
  coords.py
  gtp_cmd_handlers.py
  gtp_engine.py
  gtp_extensions.py
  gtp_wrapper.py
  main.py
  minigui/minigui.ts
  oneoffs/position_pv.py
  player_interface.py
  requirements.txt
  strategies.py
  tests/test_coords.py
  tests/test_strategies.py
Labels: size/XXL

#217 Write output SGFs using tensorflow so we can write directory to GCS.
  cc/BUILD
  cc/file/BUILD
  cc/file/filesystem.cc
  cc/file/helpers.cc
  cc/file/helpers.h
  cc/main.cc
  cc/tf_utils.cc
  cc/tf_utils.h
Labels: size/L

#218 Fix gke gpu scheduling
  cluster/selfplay/cc-player.yaml
  cluster/selfplay/cc_wrapper.sh
  cluster/selfplay/gpu-player.yaml
Labels: lgtm, size/S

#220 Fix example buffer to use absl.flags, fix logic error
  example_buffer.py
Labels: size/XS

#221 Stop duplicating komi in every signal node in the tree.
  cc/dual_net_test.cc
  cc/gtp_player.cc
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player_test.cc
  cc/position.cc
  cc/position.h
  cc/position_benchmark.cc
  cc/position_test.cc
  cc/test_utils.cc
  cc/test_utils.h
Labels: size/L

#223 Build toco as part of the C++ tensorflow setup.
  cc/configure_tensorflow.sh
Labels: size/XS

#222 Move the TensorFlow-specific code out of DualNet into a new TfDualNet subclass.
  cc/BUILD
  cc/dual_net.cc
  cc/dual_net.h
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/main.cc
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/tf_dual_net.cc
  cc/tf_dual_net.h
Labels: size/L

#227 update holdout amount, resign threshold
  cluster/selfplay/cc_wrapper.sh
Labels: size/XS

#219 update cc_wrapper.sh to set CUDA_VISIBLE_DEVICES
  cluster/selfplay/cc-Dockerfile
  cluster/selfplay/cc-player.yaml
Labels: lgtm, size/XS

#147 Add a 'model zoo' evaluation watcher
  cluster/common.sh
  cluster/evaluator/Dockerfile.gpu
  cluster/evaluator/Makefile
  cluster/evaluator/evaluator_wrapper.sh
  cluster/evaluator/gpu-evaluator.yaml
  cluster/evaluator/launch_eval.py
  evaluation.py
  main.py
  notes.txt
  requirements.txt
  yomi/README.md
  yomi/simple_eval.py
Labels: size/L

#224 Replace dual_net hyperparams with flags
  dual_net.py
  local_rl_loop.py
  main.py
  preprocessing.py
  tests/test_dual_net.py
  tests/test_flags
Labels: size/L

#229 updates from training box: validate on last 30. adjust freq of updat…
  dual_net.py
  notes.txt
  rl_loop.py
Labels: size/M

#230 Add ponder & courtesy pass to C++ GTP mode
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/main.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  minigui/serve.py
Labels: size/L

#232 Log random seed & MctsPlayer options to stderr on startup.
  cc/mcts_player.cc
  cc/position.cc
  cc/position.h
Labels: size/S

#234 Fix bugs in BoardVisitor & GroupVisitor. Add Tests.
  cc/position.h
  cc/position_test.cc
Labels: size/M

#231 Put C++ GTP command handlers into a map & add known_command support.
  cc/BUILD
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/mcts_player.cc
  minigui/gtp_socket.ts
  minigui/serve.py
Labels: size/L

#237 Add saved_models/ to .gitignore
  .gitignore
Labels: size/XS

#244 Fix Heatmap oneoff script
  oneoffs/heatmap.py
Labels: size/S

#240 Added more tensorboard metrics
  dual_net.py
  preprocessing.py
Labels: size/M

#245 Adds 'eval' mode to cc/main, to play a game between different networks
  cc/file/path.h
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/main.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  notes.txt
Labels: size/L
