Repository tensorflow/minigo, pull requests merged in 2019-10, with the labels that each got.

#903 Variadic features
  cc/BUILD
  cc/dual_net/BUILD
  cc/dual_net/dual_net.cc
  cc/dual_net/dual_net.h
  cc/dual_net/dual_net_test.cc
  cc/dual_net/fake_dual_net.cc
  cc/dual_net/fake_dual_net.h
  cc/dual_net/lite_dual_net.cc
  cc/dual_net/lite_dual_net.h
  cc/dual_net/random_dual_net.cc
  cc/dual_net/random_dual_net.h
  cc/dual_net/tf_dual_net.cc
  cc/dual_net/tf_dual_net.h
  cc/dual_net/tpu_dual_net.cc
  cc/dual_net/tpu_dual_net.h
  cc/gtp_client.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/model/BUILD
  cc/model/batching_model.cc
  cc/model/batching_model.h
  cc/model/batching_model_test.cc
  cc/model/buffered_model.cc
  cc/model/buffered_model.h
  cc/model/features.h
  cc/model/features_internal.h
  cc/model/features_test.cc
  cc/model/inference_cache.cc
  cc/model/inference_cache.h
  cc/model/inference_cache_test.cc
  cc/model/model.cc
  cc/model/model.h
  cc/model/reloading_model.cc
  cc/model/reloading_model.h
  cc/model/types.h
  cc/platform/utils.h
  cc/selfplay.cc
  cc/tf_bt_utils_dummy.cc
  cc/tf_utils.cc
  cc/tf_utils.h
Labels: size/XXL

#890 Target pruning & avoid playing a move in bensons-regions.
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/selfplay.cc
Labels: size/L

#910 actually apply symmetries to the input features
  cc/model/features.h
  cc/model/features_test.cc
Labels: size/M

#905 Update validate.py for new holdout paths
  ml_perf/flags/9/validate.flags
  ml_perf/reference_implementation.py
  validate.py
Labels: size/M

#911 replace comprehension with generator expression. (why isnt this a lint?)
  validate.py
Labels: size/XS

#913 remove BoardVisitor and GroupVistor members from Position
  cc/game.h
  cc/gtp_client.cc
  cc/logging.cc
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/position.cc
  cc/position.h
  cc/position_test.cc
  cc/replay_games.cc
  cc/test_utils.cc
  cc/test_utils.h
Labels: size/L

#918 "Rate_subdir" utility
  ml_perf/reference_implementation.py
  ratings/cbt_ratings.py
  ratings/math_ratings.py
  ratings/rate_subdir.py
  ratings/sqlite_ratings.py
Labels: size/L

#923 Set value init penalty option from flag in eval.cc
  cc/eval.cc
Labels: size/XS

#920 Adds `//cc:concurrent_selfplay`.
  cc/BUILD
  cc/README.md
  cc/concurrent_selfplay.cc
  cc/config/BUILD
  cc/dual_net/BUILD
  cc/dual_net/dual_net_test.cc
  cc/dual_net/factory.cc
  cc/dual_net/factory.h
  cc/dual_net/fake_dual_net.cc
  cc/dual_net/lite_dual_net.cc
  cc/dual_net/random_dual_net.cc
  cc/dual_net/tf_dual_net.cc
  cc/dual_net/tf_dual_net.h
  cc/dual_net/tpu_dual_net.cc
  cc/dual_net/tpu_dual_net.h
  cc/eval.cc
  cc/game.cc
  cc/game.h
  cc/game_utils.cc
  cc/game_utils.h
  cc/gtp.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/mcts_tree.cc
  cc/mcts_tree.h
  cc/mcts_tree_test.cc
  cc/minigui_gtp_client.cc
  cc/model/BUILD
  cc/model/batching_model.cc
  cc/model/batching_model.h
  cc/model/batching_model_test.cc
  cc/model/buffered_model.cc
  cc/model/inference_cache.cc
  cc/model/inference_cache.h
  cc/model/model.cc
  cc/model/model.h
  cc/model/reloading_model.cc
  cc/puzzle.cc
  cc/random.h
  cc/selfplay.cc
  cc/simple_example.cc
  cc/thread.h
  minigui/control/minigo_tf.ctl
  ml_perf/README.md
  ml_perf/flags/9/bootstrap.flags
  ml_perf/flags/9/rl_loop.flags
  ml_perf/flags/9/selfplay.flags
  ml_perf/reference_implementation.py
Labels: size/XXL

#925 adds a script to inspect training examples
  go.py
  oneoffs/inspect_examples.py
Labels: size/L

#926 use absl flags & app, not tf
  oneoffs/compare_examples.py
  oneoffs/inspect_examples.py
Labels: size/M

#927 Check examples
  oneoffs/inspect_examples.py
Labels: size/S

#928 Disable pass during bootstrap games, tweak features
  cc/concurrent_selfplay.cc
  cc/dual_net/dual_net_test.cc
  cc/mcts_player.cc
  cc/mcts_player_test.cc
  cc/mcts_tree.cc
  cc/mcts_tree.h
  cc/mcts_tree_test.cc
  cc/model/features.h
  features.py
  mask_flags.py
  ml_perf/flags/9/bootstrap.flags
  ml_perf/flags/9/selfplay.flags
  ml_perf/reference_implementation.py
  ml_perf/utils.py
  tests/test_features.py
Labels: size/L

#893 [EvalServer] AddModel.py to add models to models_for_eval
  cluster/common.sh
  cluster/eval_server/add_model.py
  cluster/unset-common.sh
  cluster/utils.sh
  cluster/var-status.sh
  oneoffs/cbt_models.py
Labels: size/L

#919 [EvalServer] Add ringmaster_evaluator
  bigtable_input.py
  bigtable_output.py
  cluster/eval_server/add_model.py
  cluster/evaluator/Dockerfile-ringmaster
  cluster/evaluator/Makefile
  cluster/evaluator/evaluator_ringmaster_wrapper.py
  cluster/evaluator/evaluator_ringmaster_wrapper.sh
  oneoffs/cbt_eval_sgfs.py
  oneoffs/cbt_models.py
Labels: size/L

#930 Update README.md with add_model.py details
  cluster/eval_server/README.md
Labels: size/M
