Repository tensorflow/minigo, pull requests merged in 2019-03, with the labels that each got.

#735 Makes eval runner able to load flags, cleans up
  WORKSPACE
  cc/eval.cc
  cluster/README.md
  cluster/evaluator/Dockerfile-cc
  cluster/evaluator/Makefile
  cluster/evaluator/cc-evaluator.yaml
  cluster/evaluator/evaluator_cc_wrapper.sh
  cluster/evaluator/launch_eval.py
  mask_flags.py
  rl_loop/fsdb.py
Labels: size/L

#744 fix crash after loading an SGF that ends in consecutive passes
  cc/eval.cc
  cc/game.cc
  cc/game.h
  cc/gtp.cc
  cc/gtp_player.cc
  cc/gtp_player.h
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/minigui_player.cc
  cc/minigui_player.h
  cc/puzzle.cc
  cc/selfplay.cc
  cc/simple_example.cc
  cc/zobrist.cc
Labels: size/XL

#746 add a num_games flag to selfplay
  cc/selfplay.cc
  ml_perf/flags/19/selfplay.flags
  ml_perf/flags/9/selfplay.flags
Labels: size/M

#747 Fix flags for ml perf
  ml_perf/flags/19/bootstrap.flags
  ml_perf/flags/19/rl_loop.flags
  ml_perf/flags/19/selfplay.flags
  ml_perf/flags/19/train.flags
  ml_perf/flags/9/bootstrap.flags
  ml_perf/flags/9/rl_loop.flags
  ml_perf/flags/9/selfplay.flags
  ml_perf/flags/9/train.flags
  preprocessing.py
  train.py
  validate.py
Labels: size/M

#763 fix a bad merge
  ml_perf/README.md
  ml_perf/reference_implementation.py
Labels: size/XS

#765 Add an option run run selfplay, eval & validate in parallel
  dual_net.py
  ml_perf/reference_implementation.py
Labels: size/L

#766 print detail win stats
  cc/BUILD
  cc/eval.cc
  cc/game.cc
  cc/game.h
  cc/game_utils.cc
  cc/game_utils.h
  cc/mcts_player.cc
  cc/selfplay.cc
  ml_perf/reference_implementation.py
Labels: size/L

#769 copy flag files into output directory, write log files
  cc/eval.cc
  ml_perf/reference_implementation.py
Labels: size/S

#770 print $EVAL_VERSION_TAG
  cluster/var-status.sh
Labels: size/XS

#779 Convert to double quote docstrings per PEP257
  dual_net.py
  go.py
  gtp.py
  mask_flags.py
  mcts.py
  oneoffs/oneoff_utils.py
  oneoffs/prepare_bigquery.py
  preprocessing.py
  selfplay.py
  sgf_wrapper.py
  strategies.py
  tests/test_preprocessing.py
Labels: size/L

#780 Update pip requirements.
  requirements.txt
Labels: ok-to-test, size/XS

#775 rewrite how minigui loads SGF files
  cc/minigui_player.cc
  cc/minigui_player.h
  minigui/README.md
  minigui/serve.py
  minigui/static/study.html
  minigui/static/study.js
  minigui/study.ts
Labels: size/L

#781 update all flags with final values
  ml_perf/flags/9/architecture.flags
  ml_perf/flags/9/bootstrap.flags
  ml_perf/flags/9/eval.flags
  ml_perf/flags/9/rl_loop.flags
  ml_perf/flags/9/selfplay.flags
  ml_perf/flags/9/train.flags
  ml_perf/flags/9/validate.flags
Labels: size/M

#773 use a normal distribution instead of uniform for RandomDualNet
  cc/dual_net/factory.cc
  cc/dual_net/random_dual_net.cc
  cc/dual_net/random_dual_net.h
Labels: size/S

#787 Lazily get a model's name
  cc/eval.cc
  cc/selfplay.cc
Labels: size/M

#789 Update flags for better convergence
  ml_perf/eval_models.py
  ml_perf/flags/9/selfplay.flags
  ml_perf/flags/9/train.flags
Labels: ok-to-test, size/S

#791 add script to repeatedly run the ml_perf reference implementation and sync results
  ml_perf/repeat_run.sh
Labels: size/M
