Repository tensorflow/minigo, pull requests merged in 2019-02, with the labels that each got.

#670 update value_init_penalty comment
  cc/eval.cc
Labels: size/XS

#672 New requirements file for upcoming project
  requirements-colab.txt
Labels: size/S

#677 Improvements to flags
  dual_net.py
  freeze_graph.py
Labels: size/M

#686 Change BOARD_SIZE default to 19
  go.py
Labels: size/XS

#687 Clean up BOARD_SIZE=19
  README.md
  bootstrap.py
  cc/README.md
  cluster/README.md
  oneoffs/distillation.py
  oneoffs/swa.py
  validate.py
Labels: size/S

#688 fixes minigui/fetch-and-run.sh
  minigui/control/minigo_py.ctl
  minigui/fetch-and-run.sh
  minigui/minigui-common.sh
Labels: size/M

#691 coordinate parsing fixes
  cc/coord.cc
  coords.py
  go.py
  gtp_cmd_handlers.py
  mcts.py
  oneoffs/prepare_bigquery.py
  selfplay.py
  strategies.py
  tests/test_coords.py
  tests/test_go.py
  tests/test_mcts.py
  tests/test_sgf_wrapper.py
  tests/test_strategies.py
Labels: size/L

#694 fix some kgs->gtp renames that got lost in a bad merge
  gtp_cmd_handlers.py
Labels: size/XS

#693 Make d-noise ratio a flag
  cc/dual_net/batching_dual_net.h
  cc/dual_net/batching_dual_net_test.cc
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/selfplay.cc
Labels: size/M

#690 make Graph beginPath, moveTo, lineTo, stroke methods private
  minigui/graph.ts
  minigui/static/graph.js
  minigui/static/vs.js
  minigui/static/winrate_graph.js
  minigui/vs.ts
  minigui/winrate_graph.ts
Labels: size/L

#676 k8s ringmaster job
  cc/gtp.cc
  cc/mcts_player.cc
  cluster/evaluator/launch_eval.py
  cluster/ringmaster/Makefile
  cluster/ringmaster/example.ctl
  cluster/ringmaster/lz-Dockerfile
  cluster/ringmaster/mggtp-Dockerfile
  cluster/ringmaster/p100-lz-tuning
  cluster/ringmaster/ringmaster.yaml
  cluster/ringmaster/ringmaster_wrapper.sh
  cluster/ringmaster/setup_ringmaster.py
  cluster/selfplay/tpu-player-deployment.yaml
  notes.txt
  ratings/ratings.py
  ratings/schema.sql
  rl_loop/fsdb.py
Labels: size/L

#698 pylint + flake8
  bigtable_input.py
  gtp_cmd_handlers.py
  preprocessing.py
  train.py
Labels: size/S

#673 RFC: Squeeze and Excitation
  dual_net.py
  tests/test_flags
Labels: size/M

#703 remove unused variables
  cluster/unset-common.sh
Labels: size/XS

#701 Add eval_games bigtable
  cc/tf_bt_utils.cc
  cluster/common.sh
  cluster/create_table.sh
  cluster/unset-common.sh
  cluster/utils.sh
  cluster/var-status.sh
Labels: size/M

#705 V17 changes
  cluster/calibrator/calibrator-deployment.yaml
  cluster/cluster-up-tpu.sh
  cluster/make-all.sh
  cluster/selfplay/tpu-player-deployment.yaml
  cluster/trainer/tpu-trainer-deployment.yaml
  rl_loop/distributed_flags
  rl_loop/distributed_flags_nr
  rl_loop/train_and_validate.py
Labels: size/M

#707 Small updates to minigui/README.md
  minigui/README.md
  minigui/fetch-and-run.sh
Labels: size/S

#709 Write eval games to bigtable
  cluster/evaluator/cc-evaluator.yaml
  cluster/evaluator/evaluator_cc_wrapper.sh
Labels: size/XS

#708 Update kPuct, replace with progressive widening formula from AZ paper. Fixes #706
  bigtable_input.py
  cc/constants.h
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  mcts.py
  tests/test_mcts.py
Labels: size/L

#714 A couple of GtpPlayer improvements
  cc/gtp_player.cc
  cc/gtp_player.h
Labels: size/M

#715 a long overdue update for cc/README.md
  cc/README.md
Labels: size/L

#730 MLPerf reference implementation
  dual_net.py
  ml_perf/README.md
  ml_perf/reference_implementation.py
Labels: size/L

#734 s/MiniGo/Minigo/
  README.md
  coords.py
  ml_perf/README.md
  tests/test_coords.py
  tests/test_dual_net.py
  tests/test_features.py
  tests/test_go.py
  tests/test_mask_flags.py
  tests/test_mcts.py
  tests/test_preprocessing.py
  tests/test_sgf_wrapper.py
  tests/test_strategies.py
  tests/test_symmetries.py
  tests/test_utils.py
Labels: size/M
