Repository tensorflow/minigo, pull requests merged in 2019-01, with the labels that each got.

#629 Support init-to-parent, init-to-loss, and FPU
  cc/main.cc
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
Labels: size/L

#631 Change name from FPU to value_init_penalty
  cc/main.cc
Labels: size/S

#636 Minor bug fixes
  cc/gtp.cc
  cc/mcts_node.cc
  cc/puzzle.cc
  minigui/serve.py
Labels: size/M

#637 remove logging of GTP command from arg-count mismatch error
  cc/gtp_player.cc
  cc/gtp_player.h
Labels: size/L

#635 Zoo-loop fixes
  cluster/evaluator/launch_eval.py
  ratings/ratings.py
Labels: size/XS

#633 V15 cleanups
  cc/constants.h
  cc/main.cc
  cc/mcts_node_test.cc
  cluster/base/Makefile
  cluster/calibrator/Makefile
  cluster/calibrator/calibrator-deployment.yaml
  cluster/evaluator/Makefile
  cluster/selfplay/Dockerfile-tpu
  cluster/selfplay/Makefile
  cluster/selfplay/tpu-player-deployment-nr.yaml
  cluster/selfplay/tpu-player-deployment.yaml
  cluster/trainer/Dockerfile
  cluster/trainer/Makefile
  cluster/trainer/tpu-trainer-deployment.yaml
  dual_net.py
  rl_loop/distributed_flags
  rl_loop/distributed_flags_nr
  rl_loop/selfplay.py
  rl_loop/train_and_validate.py
  train.py
Labels: size/L

#639 replace incorrectly named KGS coord with GTP
  cc/coord.cc
  cc/coord.h
  cc/coord_test.cc
  cc/gtp_player.cc
  cc/mcts_node.cc
  cc/mcts_node_test.cc
  cc/mcts_player_test.cc
  cc/position.cc
  cc/position_test.cc
Labels: size/L

#634 Ladder detector
  oneoffs/ladder_detector.py
Labels: size/L

#646 update dockerfiles to use new name of binary
  cluster/selfplay/Dockerfile-cc
  cluster/selfplay/Dockerfile-tpu
Labels: size/XS

#650 Update eval image
  cc/eval.cc
  cc/tf_bt_utils.cc
  cluster/evaluator/Dockerfile-cc
  cluster/evaluator/evaluator_cc_wrapper.sh
Labels: size/S

#651 add MIN TASKS check, add flag for ratings.py
  cluster/evaluator/launch_eval.py
  ratings/ratings.py
Labels: size/S

#653 remove Position::previous_move, it's a copy of MctsNode::move
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_player_test.cc
  cc/position.cc
  cc/position.h
Labels: size/M

#654 Add showboard command. Fix hang after GTP quit command
  cc/gtp_player.cc
  cc/gtp_player.h
Labels: size/S

#655 Add count score button to Minigui
  minigui/static/study.html
  minigui/static/study.js
  minigui/study.ts
Labels: size/S

#659 clean up CreateSgfString since absl::StrFormat was released
  cc/BUILD
  cc/sgf.cc
Labels: size/S

#658 rename MctsPlayer::Options batch_size to virtual_losses
  cc/eval.cc
  cc/gtp.cc
  cc/gtp_player.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/mcts_player_test.cc
  cc/minigui_player.cc
  cc/puzzle.cc
  cc/selfplay.cc
Labels: size/S

#662 fix GetStoneHistory: it should truncate short histories, not null pad
  cc/game.cc
  cc/game.h
Labels: size/S

#664 fix value_init_penalty comment
  cc/selfplay.cc
Labels: size/XS

#668 Avoid OOM on large trim operations, show progress
  bigtable_input.py
Labels: size/M
