Repository tensorflow/minigo, pull requests merged in 2019-04, with the labels that each got.

#798 Renaming in dual_net
  dual_net.py
Labels: size/M

#799 Swish
  dual_net.py
Labels: size/XS

#800 Add a normalized value_cost
  dual_net.py
Labels: size/XS

#776 [oneoff] Script to push sgfs to bigtable eval_games
  oneoffs/eval_sgf_to_cbt.py
Labels: size/L

#804 upgrade to TF 1.13, fix TPU code
  cc/BUILD
  cc/configure_tensorflow.sh
  cc/dual_net/BUILD
  cc/dual_net/factory.cc
  cc/dual_net/lite_dual_net.cc
  cc/dual_net/tpu_dual_net.cc
Labels: size/M

#805 Required version of Bazel is now v0.19.2
  README.md
  cc/README.md
Labels: size/S

#797 [oneoff] Script to push models to a new bigtable models table
  cluster/common.sh
  cluster/create_table.sh
  cluster/unset-common.sh
  cluster/utils.sh
  cluster/var-status.sh
  oneoffs/cbt_models.py
Labels: size/L

#814 update minigo version of absl to the same one used in TF 1.13.0-rc2
  WORKSPACE
  cc/coord.h
Labels: size/S

#815 Move verbose logging out of MctsPlayer and into caller
  cc/eval.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/puzzle.cc
  cc/selfplay.cc
Labels: size/L

#817 Change wins_subset SQL
  ratings/ratings.py
Labels: size/XS

#818 Prework for cbt_ratings.py
  cluster/evaluator/evaluator_cc_wrapper.sh
  oneoffs/cbt_models.py
  oneoffs/eval_sgf_to_cbt.py
  ratings/ratings.py
  ratings/schema.sql
Labels: size/M

#820 Added some artifact files to gitignore
  .gitignore
Labels: size/XS

#819 Add cbt_ratings.py backed by cbt
  ratings/cbt_ratings.py
  requirements-analysis.txt
Labels: size/L

#821 Rename oneoff/eval_sgf_to_cbt.py
  oneoffs/cbt_eval_sgfs.py
Labels: size/XS

#822 Unify cbt_ratings.py and ratings.py
  ratings/cbt_ratings.py
  ratings/ratings.py
Labels: size/L

#831 remove MctsPlayer::game and MctsPlayer::History, which aren't needed
  cc/gtp_client.cc
  cc/mcts_player.h
  cc/selfplay.cc
Labels: size/S

#832 update edgetpu model for minigui
  minigui/control/minigo_edgetpu.ctl
Labels: size/S

#833 Slide export window forward, add thinning option
  batch_exporter.py
Labels: size/M
