Repository tensorflow/minigo, pull requests merged in 2019-08, with the labels that each got.

#857 fix pylint errors
  player_interface.py
Labels: size/S

#858 update continuous integration testing notes
  testing/README.md
Labels: size/M

#860 Opening frequencies analysis & export
  oneoffs/joseki.html
  oneoffs/opening_freqs.py
  oneoffs/opening_freqs_export.py
Labels: size/XL

#861 Playout cap oscillation
  cc/eval.cc
  cc/game.cc
  cc/game.h
  cc/gtp_client.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/puzzle.cc
  cc/selfplay.cc
  cc/simple_example.cc
  cc/tf_utils.cc
  oneoffs/joseki.html
Labels: size/M

#863 More efficient implementation of Benson's Algorithm
  cc/inline_vector.h
  cc/pass_alive_test.cc
  cc/position.cc
Labels: size/L

#865 update visualizer to correctly do charts for all runs
  oneoffs/joseki.html
  oneoffs/opening_freqs_export.py
Labels: size/L

#868 reduce the size of the nlohmann json library download
  WORKSPACE
  cc/BUILD
  cc/json.BUILD
  cc/json.h
  cc/minigui_gtp_client.cc
Labels: size/M

#871 add missing parens in the definition of kMinPassAliveMoves
  cc/constants.h
Labels: size/XS

#872 pass the correct number of times to end game in //cc:eval
  cc/eval.cc
Labels: size/XS

#867 Flags for PCO
  dual_net.py
  ml_perf/flags/9/architecture.flags
  ml_perf/flags/9/selfplay.flags
Labels: size/S
