Repository tensorflow/minigo, pull requests merged in 2019-09, with the labels that each got.

#878 Adds "target pruning" for greater policy concentration & extra shine.
  cc/mcts_node.cc
  cc/mcts_node.h
  cc/mcts_node_test.cc
  cc/mcts_player.cc
  cc/mcts_player.h
  cc/selfplay.cc
Labels: size/L

#881 update comments on target pruning
  cc/mcts_node.cc
  cc/mcts_player.h
Labels: size/XS

#884 fix missing initialization of input.sym
  cc/gtp_client.cc
Labels: size/XS

#882 Symmetry-aware inference cache
  cc/BUILD
  cc/coord.cc
  cc/coord.h
  cc/init.cc
  cc/mcts_node.cc
  cc/mcts_player.cc
  cc/model/inference_cache.cc
  cc/model/inference_cache.h
  cc/model/inference_cache_test.cc
  cc/puzzle.cc
  cc/sample_records.cc
  cc/selfplay.cc
  cc/symmetries.cc
  cc/symmetries.h
  cc/symmetries_test.cc
Labels: size/XL

#885 add dump_game.py and launch_tensorboard.py
  oneoffs/dump_game.py
  oneoffs/launch_tensorboard.py
Labels: size/L

#875 Adds a "Joseki Explorer" React App
  .gitignore
  oneoffs/joseki/.gitignore
  oneoffs/joseki/README.md
  oneoffs/joseki/joseki_query.py
  oneoffs/joseki/joseki_static_report.html
  oneoffs/joseki/opening_freqs.py
  oneoffs/joseki/opening_freqs_export.py
  oneoffs/joseki/package-lock.json
  oneoffs/joseki/package.json
  oneoffs/joseki/public/favicon.ico
  oneoffs/joseki/public/index.html
  oneoffs/joseki/public/logo192.png
  oneoffs/joseki/public/logo512.png
  oneoffs/joseki/public/manifest.json
  oneoffs/joseki/src/App.css
  oneoffs/joseki/src/App.js
  oneoffs/joseki/src/App.test.js
  oneoffs/joseki/src/index.css
  oneoffs/joseki/src/index.js
  oneoffs/joseki/src/serviceWorker.js
Labels: size/XXL

#887 Add link to WORKSPACE, which sets the TF version
  cc/README.md
Labels: size/XS

#896 Add an average_winrate_observed metric to tensorboard
  dual_net.py
Labels: size/XS

#899 mlperf fixes
  ml_perf/flags/9/train.flags
  ml_perf/reference_implementation.py
  train.py
Labels: size/S

#897 add player, result, a little delay to dump_game
  oneoffs/dump_game.py
Labels: size/S

#902 Add test for pass-losing behavior
  cc/mcts_player_test.cc
Labels: size/M
